### ISSUE TITLE
Wrong icon for "Muted by you"

### ISSUE THREAD

**Issue by TillVogelsang** [davart154/Icon-Revert-2023#1]
![image](https://github.com/davart154/Icon-Revert-2023/assets/67326844/9b497dd3-d9fa-4d89-bf38-c01a6819cfbe)
The icon for "Muted by you" is actually the icon for "Server muted"

**Comment by TillDV** [comment]
![image](https://github.com/davart154/Icon-Revert-2023/assets/67326844/f78995ee-40c6-4352-ac5f-c76af85be680)

**Comment by TillDV** [comment]
Posted it to your `Themes` repo...
