### ISSUE TITLE
No Longer Works in "User Area" on Latest PTB

### ISSUE THREAD

**Issue by Avakining** [davart154/Icon-Revert-2023#12]
The revert no longer fully works on the latest PTB. Most icons are correct, but the "user area" (the place with the user's profile picture, username, status, mute/deafen controls, and settings button) now use the terrible new icons. See screenshot:

<img width="91" alt="Screenshot 2024-12-19 at 16 59 10" src="https://github.com/user-attachments/assets/c82cd967-c5b3-4f51-bc69-1a776db4c7de" />

Debug info:
```md
## Discord Info
ptb 355199 (b9176aa) Host 0.0.153 arm64 Build Override: N/A macOS 15 (24.2.0)

## BetterDiscord
stable 1.11.0
```

**Comment by davart154** [comment]
Thanks for letting me know about this, I'll fix it when I can
