### ISSUE TITLE
Chat icons do not display properly.

### ISSUE THREAD

**Issue by Halokiller990** [davart154/Icon-Revert-2023#4]
Betterdiscord v1.10.1 
Discord Stable

Current chat buttons with no plugins or themes that modify the chat buttons.
![image](https://github.com/davart154/Icon-Revert-2023/assets/48164233/555a77ef-6e45-4de7-a187-357aac72c09a)

Current appearance with my usual plugins if Icon-Revert is enabled. (RemoveChatButtons should be removing sticker and gift, + FavoriteMedia should be adding the image and video icon but replaces with other icons)
![image](https://github.com/davart154/Icon-Revert-2023/assets/48164233/d54e360d-c0a9-4ea9-a8bc-666a21f593f3)

(RemoveChatButtons + FavoriteMedia Enabled with Icon-Revert DISABLED)
![image](https://github.com/davart154/Icon-Revert-2023/assets/48164233/46176a09-1868-4632-bb75-5a31c422dcf2)

FavoriteMedia buttons still work as intended when clicked, just display the wrong icon because of Icon-Revert.

**Comment by davart154** [comment]
Thanks, I'll get to it when I can.

**Comment by EthanWinters2885** [comment]
Oh thanks, for fixing the icons, cus I had this problem too
