### ISSUE TITLE
Theme Breaks GameActivityToggle

### ISSUE THREAD

**Issue by Avakining** [davart154/Icon-Revert-2023#5]
When this theme is enabled, [GameActivityToggle](https://github.com/mwittrien/BetterDiscordAddons/tree/master/Plugins/GameActivityToggle/)'s button is replaced with a grey box (see screenshot)
<img width="123" alt="Screenshot 2024-04-15 at 15 50 53" src="https://github.com/davart154/Icon-Revert-2023/assets/25210618/99bad8f3-6be4-4d71-9d28-8d10273918a9">

ptb 284900 (725c063)

**Comment by huskyon9** [comment]
Same here 

discord version: stable 285561 (e592eef)
with import icon revert css like this:
![image](https://github.com/davart154/Themes/assets/124596711/989d9610-5e82-41f3-8f01-d857770576aa)

with out import icon revert css like this:
![image](https://github.com/davart154/Themes/assets/124596711/fb9737a3-530d-420d-be1b-cd587d78170c)
