### ISSUE TITLE
New update broken some icons

### ISSUE THREAD

**Issue by nshjck** [davart154/Icon-Revert-2023#6]
![image](https://github.com/davart154/Icon-Revert-2023/assets/123022316/ee9008ab-6011-440c-8ee4-8ec1bbd349d2)

Most icons in the bottom left menu appear to be using the new versions after the most recent discord update today. (Screenshot taken with only Vencord and this theme enabled)

**Comment by davart154** [comment]
Class update, will fix when available.

**Comment by nshjck** [comment]
incredible, thanks <3

**Comment by ljcool2006** [comment]
@davart154 did you forget to update the theme? github still says the theme hasn't been updated since last month

**Comment by davart154** [comment]
I thought I had merged someone's commit but ig I gotta do it myself
